#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") PROMPT [silent]

'$(basename "$0")' asks for user input and prints
the entered text on stdout.
When 'silent' is added as a second argument, the
input is not shown on the screen during typing.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

value=

if [ "$2" = "silent" ]; then
    echo -n "$1: " >&2 && read -s value
else
    echo -n "$1: " >&2 && read value
fi

echo "$value"

