#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") PROMPT

'$(basename "$0")' asks for user input and prints
the entered text on stdout.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

value=
echo -n "$1: " >&2 && read value
echo "$value"

