#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") DIR

'$(basename "$0")' converts a Minecraft world in the Spigot folder
layout to the Vanilla folder layout.

DIR is the Spigot world. A sibling directory called "DIR-vanilla"
is created containing Overworld, Nether & End in Vanilla format.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#

spigotDir="$(readlink -f $1)"
try test -d "$spigotDir"

vanillaDir="${spigotDir}-vanilla"

# Create vanilla Overworld
try test ! -d "$vanillaDir"
try cp -r "$spigotDir" "$vanillaDir"
try test -d "$vanillaDir/world/"
try mv "$vanillaDir/world"/* "$vanillaDir/"
try rm -rf "$vanillaDir/world/"
echo Created: $vanillaDir

# Create vanilla Nether, if any
if [ -d "${vanillaDir}/world_nether/DIM-1" ]; then
    try mv "${vanillaDir}/world_nether/DIM-1" "${vanillaDir}"
    try rm -rf "$vanillaDir/world_nether/"
    echo "Created: ${vanillaDir}/DIM-1/"
fi

# Create vanilla End, if any
if [ -d "${vanillaDir}/world_the_end/DIM1" ]; then
    try mv "${vanillaDir}/world_the_end/DIM1" "${vanillaDir}"
    try rm -rf "$vanillaDir/world_the_end/"
    echo "Created: ${vanillaDir}/DIM1/"
fi
